-- AlterTable
ALTER TABLE "plans" ADD COLUMN     "banners" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "users" INTEGER NOT NULL DEFAULT 2,
ALTER COLUMN "sales" SET DEFAULT 10,
ALTER COLUMN "prices" SET DEFAULT 100,
ALTER COLUMN "cost" SET DEFAULT 0;
