import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import './globals.css'
import { TailwindIndicator } from '@/components/tailwind-indicator'
import { Toaster } from '@/components/ui/sonner'
import Providers from './_components/providers'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className={fontSans.variable}>
        {/* <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} /> */}
        <Providers>
          <main>{children}</main>
        </Providers>
        <TailwindIndicator />
        <Toaster />
      </body>
    </html>
  )
}
